# To configure environment variables, create or modify the .docker.env files in each project
services:
  db:
    image: mysql:8.4
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3636:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root # Don't do this normally
    networks:
      - app_network

  backend:
    build: backend/
    restart: always
    volumes:
      - static_files:/backend/build/static
    ports:
      - "8000:8000"
    environment:
      - LISTEN_ADDR=0.0.0.0
    networks:
      - app_network

  frontend:
    build: frontend/
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

secrets:
  jwt_secret:
    file: jwt_secret.txt

volumes:
  db_data:
  static_files:
